In [40]:
import numpy as np
from numpy import sqrt,tanh,sinh,cosh,exp,pi,arctanh
from scipy.special import factorial
dtype=np.complex128
# float64 1.7E +/- 308 (15 digits)

In [41]:
def LadderOperator(s):
    n=int(2*s+1)
    rtval=np.zeros((n,n))
    for i in range(n-1):
        m=-s+i
        rtval[i+1,i]=sqrt(s*(s+1)-m*(m+1))
    return rtval

print(LadderOperator(2))
print(np.linalg.matrix_power(LadderOperator(2),4))

[[0.         0.         0.         0.         0.        ]
 [2.         0.         0.         0.         0.        ]
 [0.         2.44948974 0.         0.         0.        ]
 [0.         0.         2.44948974 0.         0.        ]
 [0.         0.         0.         2.         0.        ]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [24.  0.  0.  0.  0.]]


In [42]:
def getTh(th,m12):
    #m12=m1/m2
    value1=m12+cosh(th)+sqrt(1+m12**2+2*m12*cosh(th))
    value2=sinh(th)/value1
    return 4*arctanh(value2)

In [43]:


def Amn(m,n,th,th1,th2,C1,C2):
    t=np.arange(m+1)
    k=np.arange(n+1)

    sum1=np.sum(C1[t]*tanh(-th1/4)**(m-t)/(factorial(t)*factorial(m-t)))
    sum2=np.sum(C2[k]*tanh(-th2/4)**(n-k)/(factorial(k)*factorial(n-k)))

    sum3=np.sum(C1[t]*tanh(th1/4)**(m-t)/(factorial(t)*factorial(m-t)))
    sum4=np.sum(C2[k]*tanh(th2/4)**(n-k)/(factorial(k)*factorial(n-k)))

    prod1=exp(2*th)/4*sum1*sum2
    prod2=exp(-2*th)/4*sum3*sum4*(-1)**(m+n)

    return factorial(m+n-1)/sinh(th)*(prod1+prod2)


C1=np.ones(999)
C2=np.ones(999)

print(Amn(m=16,n=16,th=.9,th1=.9,th2=.9,C1=C1,C2=C2))
print(Amn(m=32,n=32,th=.9,th1=.9,th2=.9,C1=C1,C2=C2))
print(Amn(m=64,n=64,th=.9,th1=.9,th2=.9,C1=C1,C2=C2))



453634168.1116386
4.148376391790536e+20
9.755327810752304e+44


In [55]:

th=.9
r1=r2=b=1.0
m1=m2=1.0
s1=s2=2

def Chi(s1,s2,m1,m2,r1,r2,b,th,C1,C2):
    b=np.array(b,dtype=dtype)
    th1,th2=getTh(th,m1/m2),getTh(th,m2/m1)
    
    coeff1=-2*pi**2*sqrt(r1*r2*m1*m2)/abs(b)
    sum1=np.zeros(((2*s1+1)*(2*s2+1),)*2)

    J1p,J2p=LadderOperator(s1),LadderOperator(s2)
    J1pm=np.eye(2*s1+1)
    for m in range(2*s1+1):
        J2pn=np.eye(2*s2+1)
        for n in range(2*s2+1):

            coeff2=Amn(m=m,n=n,th=th,th1=th1,th2=th2,C1=C1,C2=C2)
            coeff3=1.0/(m1**m*m2**n*np.abs(b)**(m+n-1))

            mat1=np.kron(J1pm,J2pn)
            mat2=(1j)**(m+n)*mat1.T+(-1j)**(m+n)*mat1
            print(m,n,mat1.shape)

            sum1=sum1+coeff2*coeff3*mat2

            J2pn=J2p@J2pn
        J1pm=J1p@J1pm
    return coeff1*sum1

chi=Chi(s1=16,s2=16,m1=1,m2=1,r1=1,r2=1,b=1,th=.9,C1=C1,C2=C2)

0 0 (1089, 1089)
0 1 (1089, 1089)
0 2 (1089, 1089)
0 3 (1089, 1089)
0 4 (1089, 1089)
0 5 (1089, 1089)
0 6 (1089, 1089)
0 7 (1089, 1089)
0 8 (1089, 1089)
0 9 (1089, 1089)
0 10 (1089, 1089)
0 11 (1089, 1089)
0 12 (1089, 1089)
0 13 (1089, 1089)
0 14 (1089, 1089)
0 15 (1089, 1089)
0 16 (1089, 1089)
0 17 (1089, 1089)
0 18 (1089, 1089)
0 19 (1089, 1089)
0 20 (1089, 1089)
0 21 (1089, 1089)
0 22 (1089, 1089)
0 23 (1089, 1089)
0 24 (1089, 1089)
0 25 (1089, 1089)
0 26 (1089, 1089)
0 27 (1089, 1089)
0 28 (1089, 1089)
0 29 (1089, 1089)
0 30 (1089, 1089)
0 31 (1089, 1089)
0 32 (1089, 1089)
1 0 (1089, 1089)
1 1 (1089, 1089)
1 2 (1089, 1089)
1 3 (1089, 1089)
1 4 (1089, 1089)
1 5 (1089, 1089)
1 6 (1089, 1089)
1 7 (1089, 1089)
1 8 (1089, 1089)
1 9 (1089, 1089)
1 10 (1089, 1089)
1 11 (1089, 1089)
1 12 (1089, 1089)
1 13 (1089, 1089)
1 14 (1089, 1089)
1 15 (1089, 1089)
1 16 (1089, 1089)
1 17 (1089, 1089)
1 18 (1089, 1089)
1 19 (1089, 1089)
1 20 (1089, 1089)
1 21 (1089, 1089)
1 22 (1089, 1089)
1 23 (1089, 

KeyboardInterrupt: 

In [50]:
np.min(np.abs(chi))

0.0